# Linear Combination 

In this notebook you will learn how to solve linear combination problems using the python package [NumPy](http://www.numpy.org/) and its linear algebra subpackage [linalg](https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.linalg.html). This lab is provided to prepare you for the linear algebra you will be using in Neural Networks. 

## Determining a Vector's span

From the lesson on linear combination, recall that the set of all possible vectors that you can reach with a linear combination of a given pair of vectors is called the span of those two vectors. Let's say we are given the pair of vectors $\vec{v}$ and $\vec{w}$, and we want to determine if a third vector $\vec{t}$ is within their span. If vector $\vec{t}$ is determined to be within their span, this means that $\vec{t}$ can be written as a linear combination of the pair of vectors $\vec{v}$ and $\vec{w}$. 

This could be written as:

$\hspace{1cm}a\vec{v} + b\vec{w} = \vec{t}$,$\hspace{0.3cm}$where $\vec{v}$ and $\vec{w}$ are multiplied by scalars $a$ and $b$ and then added together to produce vector $\vec{t}$. 

$\hspace{1.2cm}$*Equation 1*

This means if we can find a set of values for the scalars $a$ and $b$ that make *equation 1* true, then $\vec{t}$ is within the span of $\vec{v}$ and $\vec{w}$. Otherwise, if there is **no** set of values of the scalars $a$ and $b$ that make *equation 1* true, then $\vec{t}$ is **not** within their span. 




We can determine a vector's span computationally using NumPy's linear algebra subpackage [linalg](https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.linalg.html). Below we will go through an example below. 

If the vectors have the following values:
    
$\hspace{1cm}\vec{v} = \begin{bmatrix} 1\\ 3\end{bmatrix}$
$\hspace{0.3cm}\vec{w} = \begin{bmatrix} 2\\ 5\end{bmatrix}$ 
$\hspace{0.3cm}\vec{t} = \begin{bmatrix} 4\\ 11\end{bmatrix}$    

We can rewrite $a\vec{v} + b\vec{w} = \vec{t}$ as: 
    
$\hspace{1cm} a \begin{bmatrix} 1\\ 3\end{bmatrix} + b \begin{bmatrix} 2\\ 5\end{bmatrix} = \begin{bmatrix} 4\\ 11\end{bmatrix}$ 

In a linear algebra class you might have solved this problem by hand, using reduced row echelon form and rewriting *equation 1* as the augmented matrix. We have provided the augmented matrix for *equation 1* below. 

$
\hspace{1cm}
\left[
\begin{array}{cc|c}
1 & 2  & 4 \\
3 & 5 & 11 \\
\end{array}
\right]
$

Notice that the augmented matrix's right side contains the vector $\vec{t}$. This is the vector that we are trying to determine if it's contained within the span of the other vectors, $\vec{v}$ and $\vec{w}$. Those other vectors whose span we are checking, compose the left side of the augmented matrix.

## Determining Span Computationally
Instead of solving the problem by hand, we are going to solve this problem computationally using NumPy's linear algebra subpackage ([linalg](https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.linalg.html)) .

**Steps to Determine a Vector's Span Computationally**:

1. Make the [NumPy](http://www.numpy.org/) Python package available using the import method   
&nbsp;     
2. Create right and left sides of the augmented matrix         
    1. Create a [NumPy vector](https://docs.scipy.org/doc/numpy-1.13.0/user/basics.creation.html) $\vec{t}$ to represent the right side of the augmented matrix.    
    2. Create a [NumPy matrix](https://docs.scipy.org/doc/numpy-1.13.0/user/basics.creation.html) named $vw$ that represents the left side of the augmented matrix ($\vec{v}$ and $\vec{w}$)  
    &nbsp;    
3. Use NumPy's [**linalg.solve** function](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.linalg.solve.html#numpy.linalg.solve) to check a vector's span computationally by solving for the scalars that make the equation true. For this lab you will be using the *__check_vector_span__* function you will defined below. 

With the Python code below, you will have completed steps **1** and **2** from the list above.

In [2]:
import numpy as np
import matplotlib.pyplot
%matplotlib inline


In [4]:
#making vector t
t=np.array([4,11])
vw=np.array([[1,2],[3,5]])
# printing both
print("\nmatirx vw:",vw,"\n vector t:",t)


matirx vw: [[1 2]
 [3 5]] 
 vector t: [ 4 11]


### TODO: Check Vector's Span with *__linalg.solve__* function
You will be using NumPy's [**linalg.solve** function](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.linalg.solve.html#numpy.linalg.solve)
to check if vector $\vec{t}$ is within the span of the other two vectors, $\vec{v}$ and $\vec{w}$. To complete this task, you will be inserting your code into the function *__check_vector_span__* that is defined in the coding cell below.

**Note the Following**:
- Use the [**linalg.solve** function](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.linalg.solve.html#numpy.linalg.solve) to solve for the scalars (**vector_of_scalars**) that will make *equation 1* above 
**true**, *ONLY* when the vector that's being checked (**vector_to_check**) is within the span of the other vectors (**set_of_vectors**).   

                                      
- *Otherwise*, the vector (**vector_to_check**) is **not** within the span and an empty vector is returned.  
                                      
                                      
                                      
Below you will find the definitions of the parameters and returned variable to help you with this task. 

- **Function Parameters:**
    - **set_of_vectors** is the left side of the augmented matrix. This parameter represents the set of vectors (e.g. $\vec{v}$ and $\vec{w}$) whose span you are checking.
    - **vector_to_check** is the right side of the augmented matrix. This parameter represents the vector (e.g. $\vec{t}$) that's checked to see if it's within the span of the vectors in **set_of_vectors**.

                                      
- **Returned variable:** 
    - **vector_of_scalars** contains the scalars that will solve the equations **"if"** the checked vector is within the span of the set of vectors. Otherwise, this will be an empty vector. 

With the Python code below, you will be completing step **3** of *determine a vector's span computationally*. In the code below (see *__TODO:__*), you will need to replace **None** below with code that uses [**linalg.solve** function](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.linalg.solve.html#numpy.linalg.solve) to solve for the scalars (*vector_of_scalars*).

In [8]:
def vector_check_span(setOfvectors,vector2check):
# creating empty vector of correct size
    vector_of_scalars=np.asarray([None]*setOfvectors.shape[0])
    try:
        vector_of_scalars=np.linalg.solve(setOfvectors,vector2check)
        if not (vector_of_scalars is None):
            print('\n vector withing the span : ',vector_of_scalars)
    except Exception as exception_type:
           if str(exception_type)=='Singular matrix':
                print('\n no single solution ,it is not within the span')
           else:
                print("\n unexpected exception error:",exception_type)
    return vector_of_scalars

            

### Checking *check_vector_span* by Solving for Scalars
Let's see if $\vec{t}$ is within the span of vectors $\vec{v}$ and $\vec{w}$ and check the code you added to the *check_vector_span* function above. 

*Notice that*:

- There is code added to check two additional sets of vectors (see the additional vectors below).  


- To *run* your code:
    - Click on the Save icon (disk icon right under *'File'* in the menu bar above), to save your work.
    - Select *'Kernel'* and *'Restart & Run All'*, to run your code.  



The second set of vectors have the follwing values and augmented matrix:

$\hspace{1cm}\vec{v2} = \begin{bmatrix} 1\\ 2\end{bmatrix}$
$\hspace{0.3cm}\vec{w2} = \begin{bmatrix} 2\\ 4\end{bmatrix}$ 
$\hspace{0.3cm}\vec{t2} = \begin{bmatrix} 6\\ 12\end{bmatrix}$  $\hspace{0.9cm}
\left[
\begin{array}{cc|c}
1 & 2  & 6 \\
2 & 4 & 12 \\
\end{array}
\right]
$

The third set of vectors have the follwing values and augmented matrix:

$\hspace{1cm}\vec{v3} = \begin{bmatrix} 1\\ 1\end{bmatrix}$
$\hspace{0.3cm}\vec{w3} = \begin{bmatrix} 2\\ 2\end{bmatrix}$ 
$\hspace{0.3cm}\vec{t3} = \begin{bmatrix} 6\\ 10\end{bmatrix}$  $\hspace{0.9cm}
\left[
\begin{array}{cc|c}
1 & 2  & 6 \\
1 & 2 & 10 \\
\end{array}
\right]
$

With the Python code below, you will be checking the function you created with step **3** of *determine a vector's span computationally*. 

In [11]:
# Call to check_vector_span to check vectors in Equation 1
print("\nEquation 1:\n Matrix vw:", vw, "\nVector t:", t, sep="\n")
s = vector_check_span(vw,t)
# Call to check a new set of vectors vw2 and t2
vw2 = np.array([[1, 2], [2, 4]]) 
t2 = np.array([6, 12])
print("\nNew Vectors:\n Matrix vw2:", vw2, "\nVector t2:", t2, sep="\n")    
# Call to check_vector_span
s2 = vector_check_span(vw2,t2)

# Call to check a new set of vectors vw3 and t3
vw3 = np.array([[1, 2], [1, 2]]) 
t3 = np.array([6, 10])
print("\nNew Vectors:\n Matrix vw3:", vw3, "\nVector t3:", t3, sep="\n")    
# Call to check_vector_span
s3 = vector_check_span(vw3,t3)



Equation 1:
 Matrix vw:
[[1 2]
 [3 5]]

Vector t:
[ 4 11]

 vector withing the span :  [2. 1.]

New Vectors:
 Matrix vw2:
[[1 2]
 [2 4]]

Vector t2:
[ 6 12]

 no single solution ,it is not within the span

New Vectors:
 Matrix vw3:
[[1 2]
 [1 2]]

Vector t3:
[ 6 10]

 no single solution ,it is not within the span
